name: 'Clean up from tests'
description: 'Delete any existing data created by the tests'
inputs:
  github-token:
    description: "Github token to use when calling GitHub API"
    default: ""
runs:
  using: "composite"
  steps:

    - name: Delete Release
      run: |
        name="vT.E.S.T"
        release=$(gh release list | grep $name)
        [ $release ] && gh release delete "$name" --yes || exit 0
      env: 
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - name: Delete tags / branches
      run: |
        git push origin :refs/heads/develop
        git push origin :refs/heads/release/test
        git push origin :refs/tags/vT.E.S.T
        exit 0
      shell: bash